### ISSUE TITLE
Docker Compose includes images not published

### ISSUE THREAD

**Issue by samgaw** [sipcapture/homer5-docker#14]
I was asked to raise this after a chat at Kamailio World. The install docs at https://github.com/sipcapture/homer/wiki/Docker-Install say:

```
docker-compose pull
docker-compose up
```

But the docker-compose.yml file in this repo is referencing images that either don't exist or are marked as private on the Hub registry so the pull command fails. The only option is to run docker-compose build.

**Comment by adubovikov** [comment]
thanks for report. We will check it ASAP

**Comment by dougbtv** [comment]
Documentation change should fix er up, docker-compose build instead of
pull, it'd been reported before another issue mentions it'd be nice to push
em to Docker hub too!

**Comment by dougbtv** [comment]
Sorry, I mis-read this one, the readme in this project here is fine. It's in the Sipcapture Homer wiki -- sorry to add any confusion!

**Comment by lmangani** [comment]
Wiki Fixed! Apologies for missing this one
