### ISSUE TITLE
Cron inside docker do not rotate partitions

### ISSUE THREAD

**Issue by netaskd** [sipcapture/homer5-docker#2]
By default cron is not working inside container as was expected, and sipcapturing is failing after some days.

**Comment by dougbtv** [comment]
Thanks netaskd. I had noted crond might need some work (a new container
would be nice).

Any idea on the failure mode?

I had manually run the cron in my testing, but, need to memorialize it in
the Travis build.

**Comment by dougbtv** [comment]
Alright, I think I see the failure mode.... that cron script is buggin' out.

```
root@8f9b596cc999:/# crontab -l
30 3 * * * /opt/homer_rotate >> /var/log/cron.log 2>&1
root@8f9b596cc999:/# /opt/homer_rotate
DBI connect('homer_data:localhost:3306','homer_user',...) failed: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) at /opt/homer_mysql_partrotate_unixtimestamp.pl line 57.
Can't call method "prepare" on an undefined value at /opt/homer_mysql_partrotate_unixtimestamp.pl line 70.
DBI connect('homer_data:localhost:3306','homer_user',...) failed: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) at /opt/homer_mysql_partrotate_unixtimestamp.pl line 57.
Can't call method "prepare" on an undefined value at /opt/homer_mysql_partrotate_unixtimestamp.pl line 70.
```

I'll take on fixing this up and making a new container for cron itself.

Thanks again for the bug report.

**Comment by dougbtv** [comment]
Alright, I think we should be OK on this one, @netaskd -- went ahead and replicated the issue, and have it working.

Still need to follow-up on regression tests, but, I'd recommend pulling up master at head now, should be just what you're looking for.
