### ISSUE TITLE
Tables 'stats_dest_reply' and 'stats_dest_mem' do not exist when running docker compose version.

### ISSUE THREAD

**Issue by leftyb** [sipcapture/homer5-docker#22]
homer-kamailio |  9(37) ERROR: db_mysql [km_dbase.c:128]: db_mysql_submit_query(): driver error on query: Table 'homer_statistic.stats_dest_reply' doesn't exist (1146)
homer-kamailio |  9(37) ERROR: <core> [db_query.c:181]: db_do_raw_query(): error while submitting query
homer-kamailio |  9(37) ERROR: sqlops [sql_api.c:265]: sql_do_query(): cannot do the query [INSERT INTO stats_dest_reply (fr]
homer-kamailio |  9(37) ERROR: db_mysql [km_dbase.c:128]: db_mysql_submit_query(): driver error on query: Table 'homer_statistic.stats_dest_mem' doesn't exist (1146)
homer-kamailio |  9(37) ERROR: <core> [db_query.c:181]: db_do_raw_query(): error while submitting query
homer-kamailio |  9(37) ERROR: sqlops [sql_api.c:265]: sql_do_query(): cannot do the query [TRUNCATE TABLE stats_dest_mem]

**Comment by netaskd** [comment]
Try update table schemes:

```
# get container id
ID=$(docker ps |grep homer-docker|awk '{print $1}')

# update schemes
for i in configuration statistic data; do
    docker exec -it $ID bash -c "sleep 1; mysql -uhomer_user -phomer_password homer_${i} </homer-api/sql/schema_${i}.sql >/dev/null 2>&1"
done
```

**Comment by adubovikov** [comment]
heh, yep, there is the table.

just disable it removing WITH_HOMER_DEST_STATS

**Comment by dougbtv** [comment]
I went ahead and used Alexandr's suggestion as the default, so the Kamailio config is updated to not define `WITH_HOMER_DEST_STATS`
