### ISSUE TITLE
homer_configuration table still using  MyISAM for some fields.

### ISSUE THREAD

**Issue by leftyb** [sipcapture/homer5-docker#23]
Mysql has changed the default engine to InnoDB for latest verrsions (higher to  5.5).

**Comment by adubovikov** [comment]
thank you

has been fixed in the homer-api. 
https://github.com/sipcapture/homer-api/commit/23e44dc9a974c7d318b88f1995d379e8919027e9

**Comment by leftyb** [comment]
Thank you, closed issue.
