### ISSUE TITLE
New tables for Homer data are not created.

### ISSUE THREAD

**Issue by leftyb** [sipcapture/homer5-docker#24]
Looks like an issue at the homer-cron  container.

5(21) ERROR: db_mysql [km_dbase.c:128]: db_mysql_submit_query(): driver error on query: Table 'homer_data.sip_capture_registration_20161001' doesn't exist
(1146)  
5(21) ERROR: <core> [db_query.c:235]: db_do_insert_cmd(): error while submitting query  
5(21) ERROR: db_mysql [km_dbase.c:128]: db_mysql_submit_query(): driver error on query: Table 'homer_data.sip_capture_registration_20161001' doesn't exist
(1146)     

When I restart the containers, the tables are created properly for 3 days time.

**Comment by lmangani** [comment]
saint @dougbtv could you take a peek?

**Comment by leftyb** [comment]
Hi any progress on that issue?
Thank you .

**Comment by dougbtv** [comment]
I started to take a cursory glance but hadn't returned to it -- any chance
you can try running the cron script by hand (enter the container, `crontab
-l`, run that script) and show us the output [if any]).

(my apologies that I've been on the road / some life changes slowing me
down here!)

-Doug

**Comment by leftyb** [comment]
Hi @dougbtv,

Thank you very much for you response. Actually after I run the script manually tables created properly. Looks like that the cron job is not run at all. My crontab -l :

crontab -l  
30 3 \* \* \* /opt/new/homer_rotate >> /var/log/cron.log 2>&1

That is a known issue on docker and ubuntu. Will try to provide more information on that. 

Thanks again.

**Comment by leftyb** [comment]
Hi @dougbtv,

At the hommer-cron output that message is appearing : 
"Cannot make/remove an entry for the specified session"

And looks same with the issue that is solved here: http://stackoverflow.com/questions/21926465/issues-running-cron-in-docker-on-different-hosts

Will test and update.

Thank you.

**Comment by leftyb** [comment]
Ok the solution is to add:

```
# Init rotation
/opt/new/homer_rotate

# Ensure cron is allowed to run
sed -i 's/^\(session\s\+required\s\+pam_loginuid\.so.*$\)/# \1/g' /etc/pam.d/cron
```

at the end of cron/run.sh

**Comment by dougbtv** [comment]
Nice sleuthing! I'll look into adding that (and trying to write a Travis
test for it) soon, or feel free to submit a pull request, too.

Appreciate it.

**Comment by lmangani** [comment]
Thanks @dougbtv and @leftyb for nailing this down!

**Comment by dougbtv** [comment]
Alright, thanks again for the contribution of the fix. I went ahead and put in some tests for Travis to verify that the cron job runs... I've got it in PR #27

**Comment by dougbtv** [comment]
Alright, I went ahead and made the tests more reproducible, so, I think this should close out the issue. If anyone has any questions / comments, feel free to add 'em, otherwise I'm closing for now. Thanks again.
