### ISSUE TITLE
homer-docker rotation.ini

### ISSUE THREAD

**Issue by davidcsi** [sipcapture/homer5-docker#34]
Hello guys,

i'm running homer-docker as per https://github.com/sipcapture/homer-docker 
running it with docker-composer, homer-cron can't connect to mysql, i have to manually change in rotation.ini

```
    host = localhost
    port = 3306
    usesocket = 1
```
to:

```
    host = mysql
    port = 3306
    usesocket = 0
```

and execute ./homer_rotate manually to create current date's tables.

Thanks

David

**Comment by dougbtv** [comment]
Hrmmm, I should check and see if homer-cron is version pinned or not,
because that's previously worked in the past... .wonder if something
changed.

Also, wondering if there should be nightly Travis builds to account for
things that aren't version pinned as, changes can cause wonkiness like this.

**Comment by mbrooks** [comment]
I have this issue too. The homer-cron probably needs to execute itself on startup or at least attempt to check that it has executed for the day. When it missed a day, bad things happen, since the bootstrap skips this step and will only create a table when it creates a totally new mysql DB.

**Comment by dougbtv** [comment]
This one is a frustrating one to break for sure. I'm guessing this is a change in the way the homer crons run, still. I am still to look into it, but...

homer-cron does run the rotation script each time it's started (including the first time), it's here:

https://github.com/sipcapture/homer-docker/blob/master/cron/run.sh#L40

Additionally, there's also CI for it, too. But.... If there's a change, and it's not version pinned, there's no nightlies built, so.... a change would break it without CI letting us know it's broken.

https://github.com/sipcapture/homer-docker/blob/master/.travis.yml#L74-L92

**Comment by lmangani** [comment]
@dougbtv no changes AFAIK but will doublecheck

**Comment by davidcsi** [comment]
The run.sh does run the rotation, but the command is going to the wrong path, i think.

**Comment by dougbtv** [comment]
Thanks guys, appreciate the eyeballs on it for sure. I should be able to
take a look in the next day or so and rebuild and ferret out what's going
on.

**Comment by davidcsi** [comment]
Fixed with commit 
https://github.com/sipcapture/homer-docker/commit/73f6a112e79694466c378ffcc8ffa685c5ca029d

**Comment by lmangani** [comment]
Thanks @davidcsi and @dougbtv closing this for now as resolved
