### ISSUE TITLE
Modified path of mysql data & scripts in homer-api

### ISSUE THREAD

**Issue by lmangani** [sipcapture/homer5-docker#40]
Note to self, we need to update the pointers for elements using homer-api mysql scripts as the location as been changed

```homer-api/sql``` -> ```homer-api/sql/mysql```
```homer-api/scripts``` -> ```homer-api/scripts/mysql```

**Comment by dougbtv** [comment]
Thanks for the heads up!

**Comment by dougbtv** [comment]
I'll come back to this a bit, but, seeing some failures in CI when I "just update the pinned versions and change the paths"

all output here: https://travis-ci.org/dougbtv/homer-docker/jobs/212197409

thought it might be quick, but, I gotta dig in a bit. Looks like something with either priming the tables with the table rotation cron job or something along those lines.

**Comment by lmangani** [comment]
Wild first look guess, but shouldn't 
```
RUN cp -R /homer-api/scripts/mysql/. /opt/
```
be
```
RUN cp -R /homer-api/scripts/mysql/* /opt/
```
?

**Comment by dougbtv** [comment]
Worth a go :) Good eye, musta worked in the past, but, it makes more sense
to me too. giving it a try and push it through Travis to see what "he" has
to say, for kicks

**Comment by dougbtv** [comment]
I think #43 is going to fix this all up, too.
