### ISSUE TITLE
bootstrap-mysql permission denied when creating /homer-semaphore/.bootstrapped)

### ISSUE THREAD

**Issue by 00Asgaroth00** [sipcapture/homer5-docker#41]
Hi,

I've just tried to run the multiple container version of homer on a fresh install of centos-7 and docker.

When running the "docker-compose up" mysql appears to startup fine, the bootstrap.sh script then attempts to created the .bootstrapped file but this step fails with a permission denied error, which in turn causes the other containers to be in a waiting state.

```
bootstrap-mysql | Mysql is now running.
bootstrap-mysql | Beginning initial data load....
bootstrap-mysql | Creating Databases...
bootstrap-mysql | Creating Tables...
bootstrap-mysql | /bootstrap.sh: line 76: /homer-semaphore/.bootstrapped: Permission denied
bootstrap-mysql | Data bootstrapped semaphore written to /homer-semaphore/.bootstrapped
bootstrap-mysql exited with code 0
```
The containers then sit in a waiting state before they start up:
```
homer-webapp | Homer web app, waiting for MySQL
homer-cron   | Homer cron container, waiting for MySQL
homer-kamailio | Kamailio, waiting for MySQL
homer-webapp | Homer web app, waiting for MySQL
homer-cron   | Homer cron container, waiting for MySQL
homer-kamailio | Kamailio, waiting for MySQL
homer-webapp | Homer web app, waiting for MySQL
homer-cron   | Homer cron container, waiting for MySQL
homer-kamailio | Kamailio, waiting for MySQL
homer-webapp | Homer web app, waiting for MySQL
homer-cron   | Homer cron container, waiting for MySQL
homer-kamailio | Kamailio, waiting for MySQL
```

Any thoughts on this particular issue? I'm fairly new to docker so any tips on how to proceed are much appreciated.

**Comment by dougbtv** [comment]
What o/s are you running? My instinct guesses selinix enabled and it's
having trouble with permissions to write to a volume...

**Comment by 00Asgaroth00** [comment]
It's running CentOS 7 x64, I see selinux is in enforcing mode, let me disable it quick and give it another shot

**Comment by 00Asgaroth00** [comment]
hmm, now get a different error when trying to start up the containers after disabling selinux.

```
[root@docker homer-docker]# sestatus
SELinux status:                 disabled
```

trying to start the containers yields:
```
[root@docker homer-docker]# docker-compose up
Starting mysql

ERROR: for mysql  Cannot start service mysql: devmapper: Error mounting '/dev/mapper/docker-253:2-923-ecc38a86bbc8b8a7b759929cdd81d0c92daeddc546431fdc1f1e99347f0ff620' on '/var/lib/docker/devicemapper/mnt/ecc38a86bbc8b8a7b759929cdd81d0c92daeddc546431fdc1f1e99347f0ff620': invalid argument
ERROR: Encountered errors while bringing up the project.
```
If I then re-enable selinux then I'm presented with the permission denied issue while bootstrapping again.

**Comment by 00Asgaroth00** [comment]
That error seems to be a known race condition which is apparently fixed. I've just switched from loopback device storage mode to device mapper (thin pools) and I'm trying a build now with selinux disabled. I'll let you know how I get on.

**Comment by dougbtv** [comment]
Nice sleuthing!!! Curious to see how it goes. I might create an issue
related to selinux as it bothers me to disable it, intellectually speaking.
Always wind up disabling it on Fedora/CentOS when using Docker but only
because I haven't taken the time to set it up properly.

**Comment by 00Asgaroth00** [comment]
okay, the "docker-compose up" now seems to complete, but I've noticed the following error's for "homer-cron" image:

```
homer-cron   | Can't open /opt/rotation.ini: No such file or directory.
homer-cron   | Can't open /opt/rotation.ini: No such file or directory.
homer-cron   | Can't open /opt/rotation.ini: No such file or directory.
```

Is this normal for the initial startup?

**Comment by dougbtv** [comment]
Hey @00Asgaroth00 sorry for a slow reply here, but, there's a PR incoming #43 which has a number of fixes and should fix up the issues you're seeing with the cron container.

Some more detail in #42. Expect that PR to land... shortly.
