### ISSUE TITLE
startup bug?

### ISSUE THREAD

**Issue by davidcsi** [sipcapture/homer5-docker#42]
Hello,

while building up homer-docker, I see two problems:

1- run.sh tries to execute the rotating script as "/opt/homer_rotate" which doesn't exists anymore, the correct script is "/opt/homer_mysql_rotate.pl"

2- while it tries to create the webrtc tables i get for both:

DBD::mysql::db do failed: Specified key was too long; max key length is 767 bytes at opt/homer_mysql_rotate.pl line 408.
Failed to execute query [CREATE TABLE IF NOT EXISTS `webrtc_capture_all_20170329` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `micro_ts` bigint(18) NOT NULL DEFAULT '0',
  `method` varchar(100) NOT NULL DEFAULT '',
  `caller` varchar(250) NOT NULL DEFAULT '',
  `callee` varchar(250) NOT NULL DEFAULT '',
  `session_id` varchar(256) NOT NULL DEFAULT '',
  `correlation_id` varchar(256) NOT NULL DEFAULT '',
  `source_ip` varchar(60) NOT NULL DEFAULT '',
  `source_port` int(10) NOT NULL DEFAULT 0,
  `destination_ip` varchar(60) NOT NULL DEFAULT '',
  `destination_port` int(10) NOT NULL DEFAULT 0,
  `proto` int(5) NOT NULL DEFAULT 0,
  `family` int(1) DEFAULT NULL,
  `type` int(5) NOT NULL DEFAULT 0,
  `node` varchar(125) NOT NULL DEFAULT '',
  `msg` varchar(3000) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`,`date`),
  KEY `date` (`date`),
  KEY `sessionid` (`session_id`),
  KEY `correlationid` (`correlation_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8 COMMENT='20170329'
/*!50100 PARTITION BY RANGE ( UNIX_TIMESTAMP(`date`))
(PARTITION p2017032900 VALUES LESS THAN (1490832000),
PARTITION pmax VALUES LESS THAN MAXVALUE ENGINE = InnoDB) */ ;

I tried reproducing #2 on a different mysql but it doesn't happen... has this happen to anyone else?

I will make a PR to fix these two bugs once i've got them sorted out.

Regards,

David Villasmil

**Comment by adubovikov** [comment]
Did you try the last version ? IMHO it has been fixed already.

**Comment by davidcsi** [comment]
Hello Alex,

Yes, this was yesterday fresh from the repo (i pulled on my repo from the upstream repo).
Here you can see the rotation is pointing to the wrong script:

https://github.com/sipcapture/homer-docker/blob/master/cron/run.sh#L21

and the actual script is:

https://github.com/sipcapture/homer-api/blob/da13a87b8eda55d4c597ce32270521249ab21dc4/scripts/homer_mysql_rotate.pl

(/opt/homer_mysql_rotate.pl)

regards,

David

**Comment by adubovikov** [comment]
ok, thank you. We will check it ASAP

**Comment by dougbtv** [comment]
I'm running it through CI right now, I'll report back when it finishes up

**Comment by dougbtv** [comment]
Hrmmm, alright, CI didn't replicate the issue, it completed the builds and did the simple test (which is enough to get the data structures built, make a "test call" with the HEP generator, and then verify that there's results in the database [It doesn't test the UI anymore than just firing it up and seeing it the index returns a 200 OK]). 

Here's the results: https://travis-ci.org/dougbtv/homer-docker/builds/216737602

It's based on HEAD of master branch, just synced into my fork and then I just made a change to the `README.md` to push up a bogus change to kick off travis.

Hopefully I can find some time to run through it by hand, maybe I can replicate it. (I didn't read deeply into the issue, but those things *do* sound familiar, so, I'm not skeptical fwiw)

**Comment by dougbtv** [comment]
Update, now reading the logs....

From `docker logs homer-cron` we get:

```
Can't open /opt/rotation.ini: No such file or directory.
```

So potentially this is an issue that isn't tested by CI, so, it can build, but, rotation might be failing?

**Comment by davidcsi** [comment]
That's what happens to me. I also noticed webrtc tables were not created?

**Comment by dougbtv** [comment]
Alright, I've got a suite of changes ready that bump up to the latest heads for homer-ui & homer-api, and also address some fixes for homer-cron container.

I'm going to run it through CI now and see how it behaves. If it looks good, I'll run a PR through and maybe ask for another set of eyes to test it if you don't mind.

This includes a patch for working-around the key-size, by changing the key size constraint, also made a note here @ https://github.com/sipcapture/homer-api/issues/148

Looking like this will create all the necessary tables, now looking like this after being bootstrapped:

```
mysql> use homer_data;
mysql> show tables;
+-----------------------------------+
| Tables_in_homer_data              |
+-----------------------------------+
| isup_capture_all_20170330         |
| isup_capture_all_20170331         |
| isup_capture_all_20170401         |
| logs_capture                      |
| report_capture                    |
| rtcp_capture                      |
| rtcp_capture_all_20170330         |
| rtcp_capture_all_20170331         |
| rtcp_capture_all_20170401         |
| sip_capture_call_20170330         |
| sip_capture_call_20170331         |
| sip_capture_call_20170401         |
| sip_capture_registration_20170330 |
| sip_capture_registration_20170331 |
| sip_capture_registration_20170401 |
| sip_capture_rest_20170330         |
| sip_capture_rest_20170331         |
| sip_capture_rest_20170401         |
| webrtc_capture                    |
| webrtc_capture_all_20170330       |
| webrtc_capture_all_20170331       |
| webrtc_capture_all_20170401       |
+-----------------------------------+
22 rows in set (0.00 sec)
```

**Comment by davidcsi** [comment]
Nice!
I can do testing in deploying manually, you can count on me. I need this to do my PR an ASR/ACD per component :)

**Comment by dougbtv** [comment]
Looks like it didn't pass CI @ https://travis-ci.org/dougbtv/homer-docker/builds/216932850

If you want to try out what I've got so far, you can checkout the branch I have it pushed to:

```
$ git clone https://github.com/dougbtv/homer-docker.git
$ cd homer-docker/
$ git checkout version_bump
```

It's the final check that fails. The thing it's testing is that on subsequent runs of the cron -- it creates the right tables. So what I'm worried about now is that it's working during the bootstrap phase, but, fails on subsequent runs....

....aaaand, I think I see the issue. (found it, I didn't update the job in the crontab, so, that fails. fixed it and letting Travis do its thing, PR eminent!)

**Comment by dougbtv** [comment]
Alright @davidcsi pull request #43 created, it's passing CI @ https://travis-ci.org/dougbtv/homer-docker/builds/216940319

Personally I'm happy to merge into master now, but, if anyone has a hesitation, feel free to speak up

**Comment by dougbtv** [comment]
@davidcsi -- any chance to give it a whirl? Hoping no news is good news :)

**Comment by davidcsi** [comment]
Sorry i didn't report it before!
It's working A-OK :)
I will re-deploye continuously as i'm implementing an ASR/ACD feature.

Regards,

David
ᐧ

Regards,

David Villasmil
email: david.villasmil.work@gmail.com
phone: +34669448337

**Comment by dougbtv** [comment]
Awesome, glad you're giving it some mileage! I'll close out this issue for
now. Feel free to open another if you run into anything, appreciate the
feedback for sure.

**Comment by dougbtv** [comment]
I'm going to close this one down for now -- again thanks David for the report and giving some exercise to this deployment technique, as per usual -- feel free to open another issue if you encounter anything, appreciated the detailed report.
