### ISSUE TITLE
image sipcapture/homer-kamailio not found

### ISSUE THREAD

**Issue by ghost** [sipcapture/homer5-docker#5]
docker-compose pull
....

Pulling kamailio (sipcapture/homer-kamailio:latest)...
Pulling repository docker.io/sipcapture/homer-kamailio
ERROR: Error: image sipcapture/homer-kamailio not found

**Comment by dougbtv** [comment]
@B-eugen thanks for the heads up! We're currently aware of this and are expecting to automate the builds and release of these images to dockerhub, however in the meanwhile, you'll have to issue a `docker-compose build` to put together the images. Sorry for the inconvenience, for sure.

**Comment by dougbtv** [comment]
FYI also being addressed in #3

**Comment by ghost** [comment]
Omg that answer was nearly instant ;) Thank you for the info!

**Comment by dougbtv** [comment]
No prob, appreciate the report for sure!

**Comment by ghost** [comment]
@dougbtv: little hint:

cron/Dockerfile:FROM qxip/homer-webapp --> cron/Dockerfile:FROM sipcapture/homer-webapp

**Comment by dougbtv** [comment]
oops! thanks for the heads up, we gotta normalize the image naming convention, too, good eye
