### ISSUE TITLE
Can't get ket from keyserver.ubuntu.com

### ISSUE THREAD

**Issue by davidcsi** [sipcapture/homer5-docker#53]
Hello, I'm facing a problem i can't make heads or tails fro, when building docker-compose:

Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.XAXjhwUji4 --no-auto-check-trustdb --trust-model always --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-security-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-stretch-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-stretch-security-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-stretch-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-stable.gpg --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xfb40d3e6508ea4c8
gpg: requesting key 508EA4C8 from hkp server keyserver.ubuntu.com
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
?: keyserver.ubuntu.com: Host not found
gpgkeys: HTTP fetch error 7: couldn't connect: Connection timed out
ERROR: Service 'kamailio' failed to build: The command '/bin/sh -c apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xfb40d3e6508ea4c8' returned a non-zero code: 2

cat /etc/debian_version
8.7

**Comment by davidcsi** [comment]
Nevermind, restarting docker fixed the problem...

**Comment by arainero** [comment]
This happened to me as well and restarting Docker fixed it too.
