### ISSUE TITLE
homer-complete without cron for use in kubernetes?

### ISSUE THREAD

**Issue by davehorton** [sipcapture/homer5-docker#60]
Can you publish a version of homer-complete that does *not* contain homer-cron?  I see you have a `homer-cron-k8s` folder with the Dockerfile, and I would like to be able to run a k8s deployment that uses a k8s CronJob instead of the homer-cron image...

**Comment by lmangani** [comment]
@davehorton you can create your own flavour of image using the sources as starting point, or even better switch to the multicontainer setup, if you need help let us know here - there's also a baseline homer-docker [k8s](https://github.com/dougbtv/homer-docker/tree/k8s) by the perpetually awesome @dougbtv you might want to try out, too!
