### ISSUE TITLE
SIP Search results page is always empty

### ISSUE THREAD

**Issue by hitokiri82** [sipcapture/homer5-docker#62]
When making a query using the SIP search, if I choose the Result Type Table the resulting table is always empty. If I choose TEXT, COUNT or PCAP, I do get a result. 
If I check the Network tab on Chrome's developer tools, I see a request to /api/v1/search/data which contains a response with a JSON object containing all the packets for the result of the query but they are not represented in the table, which is empty.

**Comment by lmangani** [comment]
Hi @hitokiri82 did you select a time-range? could you attache the API response to check out?

**Comment by hitokiri82** [comment]
Hello @lmangani . 

Yes I did.

I've attached the request and the response. 

[request.txt](https://github.com/sipcapture/homer-docker/files/1720818/request.txt)
[response.txt](https://github.com/sipcapture/homer-docker/files/1720817/response.txt)

I noticed that the response payload seems to be missing a '}' at the end. Which would also explain the JSON errors I'm getting at the console. 

`
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at uc (angular.js:1271)
    at $b (angular.js:9460)
    at angular.js:9551
    at n (angular.js:340)
    at cd (angular.js:9550)
    at c (angular.js:10319)
    at angular.js:14792
    at r.$eval (angular.js:16052)
    at r.$digest (angular.js:15870)
`

**Comment by lmangani** [comment]
Hi @hitokiri82 I just fired up a vanilla `homer-docker` container with no modifications, sent a few packets in using `hepgen` and it all works great. I can't reproduce this - did you modify the setup in any way?

![image](https://user-images.githubusercontent.com/1423657/36163117-ada4b0c4-10e8-11e8-9af4-d925d49b9034.png)

**Comment by hitokiri82** [comment]
Only change is the port on which the webapp listens.

> root@xxxxxxxxx:/opt/homer-docker# git status
> On branch master
> Your branch is up-to-date with 'origin/master'.
> Changes not staged for commit:
>   (use "git add <file>..." to update what will be committed)
>   (use "git checkout -- <file>..." to discard changes in working directory)
> 
> 	modified:   docker-compose.yml
> 
> Untracked files:
>   (use "git add <file>..." to include in what will be committed)
> 
> 	.homer.env.swp
> 
> no changes added to commit (use "git add" and/or "git commit -a")
> root@xxxxxxxxx:/opt/homer-docker# git diff
> diff --git a/docker-compose.yml b/docker-compose.yml
> index 8c56186..f1667b6 100644
> --- a/docker-compose.yml
> +++ b/docker-compose.yml
> @@ -6,7 +6,7 @@ services:
>      build: ./webapp/.
>      image: sipcapture/homer-webapp
>      ports:
> \-      - "80:80"
> \+      - "8080:80"
>      depends_on:
>        - mysql
>      volumes:

**Comment by lmangani** [comment]
Oh! You're using the multi-container app - this is an important detail. Let me take a look there.

**Comment by hitokiri82** [comment]
Would you recommend that we use the single container version for now? It's not a problem for us. I just assumed the multi container was the latest version.

**Comment by lmangani** [comment]
Actually the multi-container might lag a little behind at this time. For sure, the current multi-container webapp was building from an outdated release, its currently rebuilding and hopefully will sort this. Please standby for a retest. Thanks for bringing this up.

**Comment by lmangani** [comment]
@hitokiri82 webapp container is updated, could you give it a shot?

**Comment by hitokiri82** [comment]
@lmangani  Search is working correctly now! Thanks a lot man.

**Comment by lmangani** [comment]
Excellent! let us know if you spot other issues and possibly, if the PCAP issue is also gone.
