### ISSUE TITLE
running-with-an-external-mysql

### ISSUE THREAD

**Issue by gudge25** [sipcapture/homer5-docker#66]
https://github.com/sipcapture/homer-docker#running-with-an-external-mysql
NOT  WORKING
DOCKER  stopped

**Comment by lmangani** [comment]
Wow, that's a short report. We provide bootstrap examples, not a guarantee they'll work out of the box - If you want to run Docker homer w/ external database you'll have to carefully customize things to your needs based on the provided examples. If you have specific questions, happy to try help.

**Comment by gudge25** [comment]
> `23T13:55:21.940944838Z DB_HOST set to: 10.0.0.1

23T13:55:21.940962357Z DB_USER set to: homer_user

23T13:55:22.006513908Z loading modules under config path: //usr/lib/x86_64-linux-gnu/kamailio/modules/

23T13:55:22.051008705Z  0(23) WARNING: <core> [core/socket_info.c:1314]: fix_hostname(): could not rev. resolve 0.0.0.0

23T13:55:22.051031495Z Listening on 

23T13:55:22.051036099Z              udp: 0.0.0.0:9060

23T13:55:22.051040278Z Aliases: 

23T13:55:22.051043962Z 

23T13:55:22.051047695Z config file ok, exiting...

23T13:55:22.086674403Z Module php5 already enabled

23T13:55:22.108055647Z Enabling module rewrite.

23T13:55:22.112874936Z To activate the new configuration, you need to run:

23T13:55:22.112884045Z   service apache2 restart

23T13:55:22.194325729Z AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.3. Set the 'ServerName' directive globally to suppress this message

23T13:55:22.217269994Z loading modules under config path: //usr/lib/x86_64-linux-gnu/kamailio/modules/

23T13:55:22.233588964Z [0;35;49m 0(41) WARNING: <core> [core/socket_info.c:1314]: fix_hostname(): could not rev. resolve 0.0.0.0

23T13:55:22.233624521Z [0;39;49mListening on 

23T13:55:22.233629499Z              udp: 0.0.0.0:9060

23T13:55:22.233633036Z Aliases: 

23T13:55:22.233648490Z 

23T13:55:22.235226765Z [0;31;49m[0;31;49m 1(42) ERROR: db_mysql [km_my_con.c:129]: db_mysql_new_connection(): driver error: Can't connect to MySQL server on '127.0.0.1' (111)

23T13:55:22.235252344Z  3(44) ERROR: db_mysql [km_my_con.c:129]: db_mysql_new_connection(): driver error: Can't connect to MySQL server on '127.0.0.1' (111)

23T13:55:22.235258571Z [0;39;49m[0;39;49m[0;31;49m[0;31;49m 3(44) ERROR: <core> [db.c:318]: db_do_init2(): could not add connection to the pool 1(42) ERROR: <core> [db.c:318]: db_do_init2(): could not add connection to the pool[0;39;49m[0;39;49m[0;31;49m[0;31;49m 1(42) ERROR: sipcapture [sipcapture.c:1146]: child_init(): unable to connect to database [mysql://homer_user:homer_password@127.0.0.1/homer_data] from capture_mode param.

23T13:55:22.235267351Z  3(44) ERROR: sipcapture [sipcapture.c:1146]: child_init(): unable to connect to database [mysql://homer_user:homer_password@127.0.0.1/homer_data] from capture_mode param.

23T13:55:22.235272063Z [0;39;49m[0;39;49m[0;31;49m[0;31;49m[0;31;49m 3(44) ERROR: <core> [core/sr_module.c:923]: init_mod_child(): Error while initializing module sipcapture (//usr/lib/x86_64-linux-gnu/kamailio/modules/sipcapture.so)

23T13:55:22.235276957Z  1(42) ERROR: <core> [core/sr_module.c:923]: init_mod_child(): Error while initializing module sipcapture (//usr/lib/x86_64-linux-gnu/kamailio/modules/sipcapture.so)

23T13:55:22.235289881Z  4(46) ERROR: db_mysql [km_my_con.c:129]: db_mysql_new_connection(): driver error: Can't connect to MySQL server on '127.0.0.1' (111)

23T13:55:22.235294152Z [0;39;49m[0;39;49m[0;39;49m[0;31;49m[0;31;49m 3(44) ERROR: <core> [core/pt.c:334]: fork_process(): init_child failed for process 3, pid 44, "udp receiver child=2 sock=0.0.0.0:9060"

23T13:55:22.235298464Z [0;31;49m 1(42) ERROR: <core> [core/pt.c:334]: fork_process(): init_child failed for process 1, pid 42, "udp receiver child=0 sock=0.0.0.0:9060"

23T13:55:22.235302657Z [0;39;49m[0;39;49m 4(46) ERROR: <core> [db.c:318]: db_do_init2(): could not add connection to the pool[0;39;49m[0;33;49m[0;33;49m 1(42) CRITICAL: <core> [main.c:1611]: main_loop(): Cannot fork

23T13:55:22.235307199Z  3(44) CRITICAL: <core> [main.c:1611]: main_loop(): Cannot fork

23T13:55:22.235311602Z [0;31;49m[0;39;49m[0;39;49m 4(46) ERROR: sipcapture [sipcapture.c:1146]: child_init(): unable to connect to database [mysql://homer_user:homer_password@127.0.0.1/homer_data] from capture_mode param.

23T13:55:22.235315976Z [0;39;49m[0;31;49m 4(46) ERROR: <core> [core/sr_module.c:923]: init_mod_child(): Error while initializing module sipcapture (//usr/lib/x86_64-linux-gnu/kamailio/modules/sipcapture.so)

23T13:55:22.235319897Z [0;39;49m[0;31;49m 4(46) ERROR: <core> [core/pt.c:334]: fork_process(): init_child failed for process 4, pid 46, "udp receiver child=3 sock=0.0.0.0:9060"

23T13:55:22.235323935Z [0;39;49m[0;33;49m 4(46) CRITICAL: <core> [main.c:1611]: main_loop(): Cannot fork

23T13:55:22.235327782Z [0;39;49m[0;31;49m 6(50) ERROR: db_mysql [km_my_con.c:129]: db_mysql_new_connection(): driver error: Can't connect to MySQL server on '127.0.0.1' (111)

23T13:55:22.235331479Z [0;39;49m[1;31;49m 0(41) ALERT: <core> [main.c:740]: handle_sigs(): child process 42 exited normally, status=255

23T13:55:22.235335167Z [0;39;49m[0;31;49m[1;31;49m 0(41) ALERT: <core> [main.c:740]: handle_sigs(): child process 44 exited normally, status=255

23T13:55:22.235339014Z  6(50) ERROR: <core> [db.c:318]: db_do_init2(): could not add connection to the pool[0;39;49m[0;39;49m[1;31;49m[0;31;49m 0(41) ALERT: <core> [main.c:740]: handle_sigs(): child process 46 exited normally, status=255

23T13:55:22.235343224Z [0;39;49m 6(50) ERROR: sipcapture [sipcapture.c:1146]: child_init(): unable to connect to database [mysql://homer_user:homer_password@127.0.0.1/homer_data] from capture_mode param.

23T13:55:22.235347038Z [0;39;49m[0;31;49m 6(50) ERROR: <core> [core/sr_module.c:923]: init_mod_child(): Error while initializing module sipcapture (//usr/lib/x86_64-linux-gnu/kamailio/modules/sipcapture.so)

23T13:55:22.275616656Z [0;39;49m[0;31;49m`

**Comment by gudge25** [comment]
why in log i see  db_mysql [km_my_con.c:129]: db_mysql_new_connection(): driver error: Can't connect to MySQL server on '127.0.0.1' (111) ????
