### ISSUE TITLE
brocken pcap file 

### ISSUE THREAD

**Issue by ghost** [sipcapture/homer5-docker#68]
i am download file after i am open wireshack 
and i have notice this file brocken

**Comment by ghost** [comment]
latest version docker compose

**Comment by ghost** [comment]
<img width="635" alt="2018-05-30 2 35 19" src="https://user-images.githubusercontent.com/25709594/40690931-20e9a5d2-63b2-11e8-86f2-6335af8fe8a0.png">

**Comment by ghost** [comment]
i am create  docker-compose 
with  only  containers and connect to external database 

version: '2'
services:

    homer:
#    build: .
     restart: always
     image: sipcapture/homer-docker
     container_name: homer


     ports:
         - "9065:9060/udp"
         - "82:80"



     environment:
        - 'dbhost=127.0.0.1'
        - 'dbuser=homer_user'
        - 'dbpass=qld501a87'


this it is work

**Comment by negbie** [comment]
It should be fixed now. Please update the homer-webapp container. Thank you.

**Comment by denyspozniak** [comment]
Hello!
I am not sure my topic is related to this issue, but I have problem in opening exported pcap file from Homer7 (hom7-hep-prom-graf).
It shows:
![image](https://user-images.githubusercontent.com/22612345/47490020-88dd7c00-d850-11e8-8d62-c4743f52e6c2.png)
