### ISSUE TITLE
docker heplify-server homer7 password default incorrect

### ISSUE THREAD

**Issue by hieupnvcc** [sipcapture/homer5-docker#69]
i tried default id password (admin/test123) but cant login homer7

**Comment by negbie** [comment]
https://github.com/sipcapture/homer-app/blob/master/seeds/01_Users.js

admin/sipcapture

**Comment by hieupnvcc** [comment]
thanks for fast reply!

**Comment by lmangani** [comment]
Fixed in readmes thanks for your report @hieupnvcc
