### ISSUE TITLE
hom7-hep-prom-graf no SIP-calls

### ISSUE THREAD

**Issue by astrakid** [sipcapture/homer5-docker#70]
hi,
using this docker compilation i don't get any SIP-calls-information in homer-webapp. not clear if it is missing in DB or just an issue with the frontend.
using hom5-hep-prom-graf everything is fine.

regards,
andre

**Comment by lmangani** [comment]
Hi @astrakid could you check if you have any data in the database and/or any errors in the container logs? are you referring to SIP search or statistics? If the latter, they're not available for H5 hybrids and only accessible from Grafana

**Comment by astrakid** [comment]
yes, in the DB homer_data, table hep_proto_1_call_20180707_1200 i can see a call:

{"sid": "1
3271507130516-487175622937@x.x.x.x", "method": "INVITE", "to_user": "080033010
00", "pid_user": "", "auth_user": "xxx", "from_user": "xxx", "ruri_user": "0800330
1000", "source_ip": "x.x.x.x", "create_date": "2018-07-07 12:26:27.012", [....]

**Comment by lmangani** [comment]
Please kill the existing search widget, create a new one for SIP protocol and CALL transaction type.
It should return results.

**Comment by astrakid** [comment]
aboslutely right! thanks!!!

**Comment by lmangani** [comment]
the "defaults" are pretty broken indeed, need a major cleanup.
