### ISSUE TITLE
Timelion examples do not work

### ISSUE THREAD

**Issue by waynemillskidals** [sipcapture/homer5-docker#72]
When trying to use your Timelion examples for the Elasticsearch (external) docker build we do not appear to get them working in ES

Usage :
**` .es(index=hep-*, timefield=@timestamp,q='measurement_name:"heplify_method_response" AND tag.method:"REGISTER" AND tag.response:"200"', metric=max:heplify_method_response.counter).derivative().abs().mvavg(1m).scale_interval(1s).yaxis(min=0).color(orange).lines(fill=2,width=1).label("RPS").legend(position=nw,showTime=true)`**

Timelion gives this error : 
**`Timelion: Error: in cell #1: Unknown argument to legend: showTime**
`

Data is being injected into ES from your docker build

![screen shot 2018-08-14 at 08 02 32](https://user-images.githubusercontent.com/29538924/44076549-7d1f27b0-9f98-11e8-9400-5e4ff33193fc.png)

**Comment by lmangani** [comment]
What version of Kibana (and consequently Timelion) are you using? The above requires at least 6.x

**Comment by waynemillskidals** [comment]
I guess thats the issue as we are running 5.6.1

I will upgrade

**Comment by lmangani** [comment]
@waynemillskidals you don't necessarily have to, just need to adjust your timelion formula to eliminate the functions it doens't feature in 5.x (such as the one it complains about)
