### ISSUE TITLE
Data too long for column msg

### ISSUE THREAD

**Issue by soulofmischief87** [sipcapture/homer5-docker#82]
Hello,

I am running the latest pull of homer docker as a single container but I am having issues storing any captures. Attaching myself to the logs displays the following:

5) ERROR: <core> [db_query.c:235]: db_do_insert_cmd(): error while submitting query
 4(405) ERROR: db_mysql [km_dbase.c:128]: db_mysql_submit_query(): driver error on query: Data too long for column 'msg' at row 1 (1406)
 4(405) ERROR: <core> [db_query.c:235]: db_do_insert_cmd(): error while submitting query
 4(405) ERROR: sipcapture [sipcapture.c:1593]: sip_capture_store(): failed to insert into database(second attempt)
 1(400) ERROR: db_mysql [km_dbase.c:128]: db_mysql_submit_query(): driver error on query: Data too long for column 'msg' at row 1 (1406)
 1(400) ERROR: <core> [db_query.c:235]: db_do_insert_cmd(): error while submitting query
 1(400) ERROR: db_mysql [km_dbase.c:128]: db_mysql_submit_query(): driver error on query: Data too long for column 'msg' at row 1 (1406)

Note that I am using opensips as the tracing agent but I am dealing with webrtc payloads which can be very large. Is there anything that can be modified within the container to allow me to deal with these large paylods? Also I don't see any of the other smaller messages. Here are my siptrace configs in opensips 2.3

loadmodule "proto_hep.so"

modparam("proto_hep", "hep_id", "[hep_dst] dockerip:9060; transport=udp; version=3")
modparam("proto_hep", "homer5_on", 1)
modparam("proto_hep", "homer5_delim", "##")
modparam("proto_hep", "hep_capture_id", 2)
loadmodule "siptrace.so"
modparam("siptrace", "trace_on", 1)

**Comment by lmangani** [comment]
You need to adjust the column lenght in your rotation.ini parameters, mind it will apply to future partitions only unless you drop the existing ones.
