### ISSUE TITLE
Using Docker Samples with Docker for Windows

### ISSUE THREAD

**Issue by haeferer** [sipcapture/homer5-docker#86]
Thx to all for the nice work,

we started using homer but had Problem to get Homer Running using the Images published on hub.docker.com. Especialy on Docker for windows

All sample scripts currently do not contain tagging informations, so the docker uses default (witch is :latest  ).
:latest is currently 9 Months old.

Using :master als Tags for the docker samples does the trick. 

Is there a reason to not move :latest

**Comment by lmangani** [comment]
The `:master` tag reflects the branch its build on - something out of our current UI process. We need to find a way to automate election to `latest` but until then, please point to the `master` images.
