### ISSUE TITLE
docker build failed.

### ISSUE THREAD

**Issue by aleczhong** [sipcapture/homer5-docker#87]
Hi,

When i try to build a webapp docker image, i encountered below error.

Sending build context to Docker daemon  13.4 MB
Step 1/30 : FROM debian:jessie
 ---> 4eb8376dc2a3
Step 2/30 : MAINTAINER L. Mangani <lorenzo.mangani@gmail.com>
 ---> Running in cb66e7be8e56
 ---> 67a4d1fec7c1
Removing intermediate container cb66e7be8e56
Step 3/30 : ENV HOME /root
 ---> Running in 6a526bb2d1ed
 ---> 773fe689c24c
Removing intermediate container 6a526bb2d1ed
Step 4/30 : ENV DEBIAN_FRONTEND noninteractive
 ---> Running in e69d992705b8
 ---> ea4b397d858d
Removing intermediate container e69d992705b8
Step 5/30 : ENV BUILD_DATE 2017-02-13
 ---> Running in 072189efc668
 ---> 187901f471e6
Removing intermediate container 072189efc668
Step 6/30 : RUN rm -fr /var/lib/apt/lists/partial/
 ---> Running in 7b471ed47c52

 ---> c639b148495f
Removing intermediate container 7b471ed47c52
### Step 7/30 : RUN apt-get update -qq
 ---> Running in 049e1e3a3e2a

W: Failed to fetch http://security.debian.org/debian-security/dists/jessie/updates/main/binary-amd64/Packages  503  Service Unavailable

E: Some index files failed to download. They have been ignored, or old ones used instead.

W: Failed to fetch http://security.debian.org/debian-security/dists/jessie/updates/main/binary-amd64/Packages  503  Service Unavailable

E: Some index files failed to download. They have been ignored, or old ones used instead.

at the same time, we can not access 
http://security.debian.org/debian-security/dists/jessie/updates/main/binary-amd64/Packages

Could you please have a check on it?

**Comment by aleczhong** [comment]
Hi,

Any update for this issue?

Thanks.

**Comment by lmangani** [comment]
Not much we can do if you can't reach the debian repository. I suggest moving on to H7 docker containers.
