### ISSUE TITLE
Implement new rotation scripts

### ISSUE THREAD

**Issue by dougbtv** [sipcapture/homer5-docker#9]
New rotation scripts @ https://github.com/sipcapture/homer-api/tree/master/scripts/new

Time to implement the latest-and-greatest

**Comment by dougbtv** [comment]
Scripts have been updated per issue @ https://github.com/sipcapture/homer-api/issues/81

Going to test against the `new-rotation` branch

**Comment by adubovikov** [comment]
can we close it ?
