### ISSUE TITLE
hom7-hep-influx_provisioning_1 - Failed to connect to chronograf port 80: Connection refused

### ISSUE THREAD

**Issue by kakarata** [sipcapture/homer5-docker#92]
Hi. Installed hom7-hep-influx with docker compose, when finished, `hom7-hep-influx_provisioning_1` container is down, and below is the log I get for that container. No other container listening on port 80. Caddy just listen on 3000, 9080, 9090 and 9093.

==================

fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz,
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz,
OK: 7 MiB in 19 packages,
Waiting for influxdb API ...,
InfluxDB Retention Policy push ...,
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current,
                                 Dload  Upload   Total   Spent    Left  Speed,
{"results":[{"statement_id":0,"messages":[{"level":"warning","text":"deprecated use of 'CREATE DATABASE homer' in a read only context, please use a POST request instead"}]}]},

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   175    0   175    0     0  87500      0 --:--:-- --:--:-- --:--:-- 87500,
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current,
                                 Dload  Upload   Total   Spent    Left  Speed,
{"results":[{"statement_id":0,"messages":[{"level":"warning","text":"deprecated use of 'CREATE RETENTION POLICY \"60s\" ON homer DURATION 4w REPLICATION 1 DEFAULT' in a read only context, please use a POST request instead"}]}]},

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   228    0   228    0     0  28500      0 --:--:-- --:--:-- --:--:-- 28500,
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current,
                                 Dload  Upload   Total   Spent    Left  Speed,
{"results":[{"statement_id":0,"messages":[{"level":"warning","text":"deprecated use of 'CREATE RETENTION POLICY \"300s\" ON homer DURATION 8w REPLICATION 1' in a read only context, please use a POST request instead"}]}]},

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   221    0   221    0     0  15785      0 --:--:-- --:--:-- --:--:-- 15785,
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current,
                                 Dload  Upload   Total   Spent    Left  Speed,
{"results":[{"statement_id":0,"messages":[{"level":"warning","text":"deprecated use of 'CREATE RETENTION POLICY \"3600s\" ON homer DURATION 16w REPLICATION 1' in a read only context, please use a POST request instead"}]}]},

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   223    0   223    0     0  74333      0 --:--:-- --:--:-- --:--:-- 74333,
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current,
                                 Dload  Upload   Total   Spent    Left  Speed,
{"results":[{"statement_id":0,"messages":[{"level":"warning","text":"deprecated use of 'CREATE RETENTION POLICY \"86400s\" ON homer DURATION 32w REPLICATION 1' in a read only context, please use a POST request instead"}]}]},

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   224    0   224    0     0  14933      0 --:--:-- --:--:-- --:--:-- 14933,
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current,
                                 Dload  Upload   Total   Spent    Left  Speed,
{"results":[{"statement_id":0,"messages":[{"level":"warning","text":"deprecated use of 'CREATE CONTINUOUS QUERY cq_300s ON homer RESAMPLE EVERY 1m BEGIN SELECT mean(*) INTO homer.\"300s\".:MEASUREMENT FROM homer.\"60s\"./.*/ GROUP BY time(5m), * END' in a read only context, please use a POST request instead"}]}]},

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   315    0   315    0     0  35000      0 --:--:-- --:--:-- --:--:-- 35000,
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current,
                                 Dload  Upload   Total   Spent    Left  Speed,
{"results":[{"statement_id":0,"messages":[{"level":"warning","text":"deprecated use of 'CREATE CONTINUOUS QUERY cq_3600s ON homer RESAMPLE EVERY 10m BEGIN SELECT mean(*) INTO homer.\"3600s\".:MEASUREMENT FROM homer.\"60s\"./.*/ GROUP BY time(1h), * END' in a read only context, please use a POST request instead"}]}]},

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   318    0   318    0     0  45428      0 --:--:-- --:--:-- --:--:-- 45428,
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current,
                                 Dload  Upload   Total   Spent    Left  Speed,
{"results":[{"statement_id":0,"messages":[{"level":"warning","text":"deprecated use of 'CREATE CONTINUOUS QUERY cq_86400s ON homer RESAMPLE EVERY 1h BEGIN SELECT mean(*) INTO homer.\"86400s\".:MEASUREMENT FROM homer.\"60s\"./.*/ GROUP BY time(1d), * END' in a read only context, please use a POST request instead"}]}]},

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   319    0   319    0     0  63800      0 --:--:-- --:--:-- --:--:-- 63800,
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current,
                                 Dload  Upload   Total   Spent    Left  Speed,
{"results":[{"statement_id":0,"messages":[{"level":"warning","text":"deprecated use of 'DROP RETENTION POLICY autogen ON homer' in a read only context, please use a POST request instead"}]}]},

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   192    0   192    0     0   187k      0 --:--:-- --:--:-- --:--:--  187k,
Chronograf Dashboard push ...,
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current,
                                 Dload  Upload   Total   Spent    Left  Speed,

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to chronograf port 80: Connection refused,
Provisioning completed! Exiting ...,

**Comment by lmangani** [comment]
Hi,

The provisioning container is supposed to execute once and stay down. The Caddy ports are proxies to the internal services, try logging on to 9080 and sending HEP to 9060 to get started.

Hope this helps!

**Comment by kakarata** [comment]
Thanks Lorenzo!
