### ISSUE TITLE
unable to share

### ISSUE THREAD

**Issue by noobchamp** [sipcapture/homer5-docker#93]
How can I configure options to share flow with "share link" or "share cloud"?

thanks

**Comment by lmangani** [comment]
Hi @noobchamp this is a feature inherited from `hepic` and not yet implemented in `homer` where there are other options up and coming such as [homer-view](https://github.com/sipcapture/homer-view-react) pending completion. 

TLDR; not yet implemented

**Comment by noobchamp** [comment]
Thanks @lmangani
