### ISSUE TITLE
no data displayed in homer web app

### ISSUE THREAD

**Issue by Mihai-CMM** [sipcapture/homer5-docker#94]
Hello, running latest /home/homer7-docker/heplify-server/hom7-prom-all
I see the containers up and running and traffic that gets into heplify-server 

,CID:3038f9736ea0d98a102f1f0c6a6c848d@10.193.14.26:5060,Vlan:0,}

2020/01/30 15:37:12.435003 decoder.go:139: DBG [hep] &HEP{Version:2,Protocol:17,SrcIP:10.193.14.26,DstIP:10.193.14.108,SrcPort:5060,DstPort:5060,Tsec:1580398632,Tmsec:62405,ProtoType:1,NodeID:2002,NodePW:,Payload:OPTIONS XXXXX SIP/2.0
Via: SIP/2.0/UDP 10.193.14.26:5060;branch=z9hG4bK60dff213
Max-Forwards: 70
From: "asterisk" <sip:asterisk@10.193.14.26>;tag=as2abcbc01

BUT I see nothing in the webui app

`CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS                   PORTS                                                                                            NAMES
83d171c9f115        sipcapture/webapp                  "/docker-entrypoint.…"   21 minutes ago      Up 5 minutes                                                                                                              homer-webapp
6aa4a0f7b912        sipcapture/heplify-server:master   "./heplify-server"       21 minutes ago      Up 5 minutes             0.0.0.0:9060->9060/tcp, 0.0.0.0:9060->9060/udp, 9090/tcp                                         heplify-server
dd6410404213        prom/node-exporter:latest          "/bin/node_exporter …"   21 minutes ago      Up 5 minutes             9100/tcp                                                                                         nodeexporter
ea0b06757047        postgres:11-alpine                 "docker-entrypoint.s…"   21 minutes ago      Up 5 minutes (healthy)   5432/tcp                                                                                         db
f38b20b7a662        prom/alertmanager:latest           "/bin/alertmanager -…"   21 minutes ago      Up 5 minutes             9093/tcp                                                                                         alertmanager
9b55369fd798        prom/prometheus:latest             "/bin/prometheus --c…"   21 minutes ago      Up 5 minutes             9090/tcp                                                                                         prometheus
54ef3397a1fd        grafana/grafana:master             "/run.sh"                21 minutes ago      Up 5 minutes (healthy)   3000/tcp                                                                                         grafana
38c0480b412d        stefanprodan/caddy                 "/sbin/tini -- caddy…"   21 minutes ago      Up 5 minutes             0.0.0.0:3000->3000/tcp, 0.0.0.0:9080->9080/tcp, 0.0.0.0:9090->9090/tcp, 0.0.0.0:9093->9093/tcp   caddy
4979017cdba5        grafana/loki:master                "/usr/bin/loki -conf…"   21 minutes ago      Up 5 minutes             80/tcp, 0.0.0.0:3100->3100/tcp`

I am also on a centos8, I have no idea how to troubleshoot this further, and I've tried all docker-compose combo without any luck.
Please let me know how to troubleshoot this issue

Thanks

**Comment by lmangani** [comment]
Hi @Mihai-CMM 

I just tested the `7.7` branch and I can spin up and send traffic without glitches. 
Let's confirm you're on the right branch first, and please perform the following:

`docker logs homer-webapp`

Please also try the following from any node enabled system:
```
git clone https://github.com/sipcapture/hepgen.js && cd hepgen.js
npm install
node hepgen.js -s {homer_ip} -p 9060 -c ./config/b2bcall_rtcp.js
```

Once it completes, go and check the UI for calls in the last 10 minutes. Feel free to attach screenshots.

**Comment by Mihai-CMM** [comment]
Thanks Lorenzo,
With hep traffic generator I can see the calls,
But I am unable to see the ones captured on my live servers though they get into heplify-server:

2020/01/30 16:00:53.271218 decoder.go:139: DBG [hep] &HEP{Version:2,Protocol:17,SrcIP:10.193.14.108,DstIP:10.193.14.26,SrcPort:5060,DstPort:5060,Tsec:1580400052,Tmsec:422120,ProtoType:1,NodeID:2002,NodePW:,Payload:SIP/2.0 200 OK
Via: SIP/2.0/UDP 10.193.14.26:5060;branch=z9hG4bK59c3e14b
From: "asterisk" <sip:asterisk@10.193.14.26>;tag=as2d275c0e
To: <sip:XXXX>;tag=c2db2929ae78408790c5d6a2e4136164
Call-Id: 77fc30140f4a8ef01755628b68020571@10.193.14.26:5060

Any idea what  to look for next?

**Comment by Mihai-CMM** [comment]
Ok, I don't know what to say , could be a browser issue though not sure why I could see the ones generated  by hep generator in real time. I've logout , opened an incognito tab added call sip search widget and pressed search button, and this time when i was redirected to {URL}/call/result I could see my results also ....

**Comment by lmangani** [comment]
Could you attach a screenshot of the home page? I just want to make sure you're on the right release.

**Comment by Mihai-CMM** [comment]
![image](https://user-images.githubusercontent.com/14325493/73467888-41fc0180-4384-11ea-9ea4-90a3ea44fd17.png)

**Comment by Mihai-CMM** [comment]
these are the  images that are used 

[root@homer-prod hom7-prom-all]# docker images
REPOSITORY                  TAG                 IMAGE ID            CREATED             SIZE
grafana/grafana             master              e15c8afe07ae        About an hour ago   234MB
postgres                    11-alpine           89ae06c2ad76        13 hours ago        152MB
sipcapture/webapp           latest              d635fb21d1a7        18 hours ago        49.2MB
grafana/loki                master              7f10e944885a        23 hours ago        46.6MB
sipcapture/heplify-server   master              05af98764549        10 days ago         22.1MB
prom/prometheus             latest              b715301fa5eb        3 weeks ago         133MB
prom/alertmanager           latest              0881eb8f169f        7 weeks ago         52.1MB
prom/node-exporter          latest              e5a616e4b9cf        7 months ago        22.9MB
stefanprodan/caddy          latest              655880563633        2 years ago         24.7MB


and 

docker inspect sipcapture/webapp
[
    {
        "Id": "sha256:d635fb21d1a74f0770d007d42e8f3e92f1aceb3f0a7d0810250d1c2f4f8be50c",
        "RepoTags": [
            "sipcapture/webapp:latest"
        ],
        "RepoDigests": [
            "sipcapture/webapp@sha256:677c03c515676b279ae95e5f388f4b6b2725ee405fa242bb022e42464e439a7d"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2020-01-29T22:16:34.108239782Z",
        "Container": "0ecd0abcd42898310358c267a777705241b42e78c20217f17767ffaa545d1afe",
        "ContainerConfig": {
            "Hostname": "0ecd0abcd428",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "#(nop) ",
                "CMD [\"/homer-app\" \"-webapp-config-path=/usr/local/homer/etc\"]"
            ],
            "Image": "sha256:31fdbca4befd920feb6bc4bdde48b0439495e7401f495a4b4f1735a228651d0c",
            "Volumes": null,
            "WorkingDir": "/",
            "Entrypoint": [
                "/docker-entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": {}
        },
        "DockerVersion": "19.03.5",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "/homer-app",
                "-webapp-config-path=/usr/local/homer/etc"
            ],
            "Image": "sha256:31fdbca4befd920feb6bc4bdde48b0439495e7401f495a4b4f1735a228651d0c",
            "Volumes": null,
            "WorkingDir": "/",
            "Entrypoint": [
                "/docker-entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": null
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 49219009,
        "VirtualSize": 49219009,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/5077c52b52453f7b92724329448468f8710caa1674a5c76f25bbb409228d328a/diff:/var/lib/docker/overlay2/617e778fcd2a7019eaa78afdc7a7bc1380a9f887470417174a9964b884bdd5d7/diff:/var/lib/docker/overlay2/78c3ce7014ae6f761b66490a462b941bfa65062fe4da2cfb36b039ea8bd08ea3/diff:/var/lib/docker/overlay2/47bef6806dab8f2d29300edae3bfb24b25dcd2af9c49dd14d0f4a3f06f5466f5/diff:/var/lib/docker/overlay2/d7ff2440aba3ed24a22ed056c5fba4325965d4177a252055175074d65ae4e31f/diff:/var/lib/docker/overlay2/e8143c1e4e0ac23ae615716cdf5b53642069f9698e28cc60367e6312c392f1e4/diff:/var/lib/docker/overlay2/0ae11fafbcea468e443b766b513fdee9026f7ef7c9a47da894f3e957391f225f/diff:/var/lib/docker/overlay2/5efd36b07712b94abc115ebd2041afe4a2e82949ac6e11d97471c019f4270644/diff",
                "MergedDir": "/var/lib/docker/overlay2/9d0a0ae9768f9e60905534765870e44c2928d4d48bd6e755b227402c5002347f/merged",
                "UpperDir": "/var/lib/docker/overlay2/9d0a0ae9768f9e60905534765870e44c2928d4d48bd6e755b227402c5002347f/diff",
                "WorkDir": "/var/lib/docker/overlay2/9d0a0ae9768f9e60905534765870e44c2928d4d48bd6e755b227402c5002347f/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:77cae8ab23bf486355d1b3191259705374f4a11d483b24964d2f729dd8c076a0",
                "sha256:798353d9d8d6e989f9d28f75780332ce98a35065970e4387fe4613c8e3c961e8",
                "sha256:f75496ec408c53948aa78089abe195658324d2c99e4360e63c814f727c49d420",
                "sha256:cb8bfc410dfd66c7765ab755b669c18cac5fd86e15ce76bf2fc9356027c5ba07",
                "sha256:b12493d45da141469396a1d4def3e02d8e7f2d668f742088b8097f306f3556ec",
                "sha256:d962a4c3571442ce0c671c1c67154b9b2c932483b9885e13dd0d91e632cb031c",
                "sha256:2d7b076706566703725e894afc7285d8e2535c934a19be80ae172bb6e2f395e7",
                "sha256:614d25b7f0d7e1c005592423ec702f171569024a5c556ef22638efd94504c0fd",
                "sha256:d0966ccfec6c2fd59f049fa5baedd6178a116769f2724675e9507d22aeab5518"
            ]
        },
        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
        }
    }
]

**Comment by lmangani** [comment]
Looks good - not sure what this might have been but it appears cache related. 
Keep in mind we push the image about once a day (nightly build) so check back for updates often, and let us know if you notice any other anomaly. Thanks for your report!
