### ISSUE TITLE
grafana returns empty results  for sip related metrics

### ISSUE THREAD

**Issue by Mihai-CMM** [sipcapture/homer5-docker#95]
Hello, I am using prom-all 7.7 version.
Looking at grafana query:

(rate(heplify_method_response{method="INVITE", response=~"50.*"}[10m]))

Looking at exposed metric:

curl localhost:9096/metrics | grep heplify 

heplify_packets_size{node_id="-sl",type="sip"} 546
heplify_packets_size{node_id="asterisk1-test",type="sip"} 546

heplify_packets_total{node_id="-sl",type="sip"} 42
heplify_packets_total{node_id="asterisk1-test",type="sip"} 42

there is no heplify_method_response in promethreus or exposed by heplify-server

docker images | grep heplify
sipcapture/heplify-server   master              05af98764549        10 days ago         22.1MB

docker image inspect 05af98764549
[
    {
        "Id": "sha256:05af9876454929f0a0df381bb592ac809915555fbbc01a3816e0c877b6614d34",
        "RepoTags": [
            "sipcapture/heplify-server:master"
        ],
        "RepoDigests": [
            "sipcapture/heplify-server@sha256:e0a5dcaad1ebc737d7ff620632a07ca20840e7c78264a56c0fb6b5678775fc2d"

**Comment by Mihai-CMM** [comment]
Hi guys, any development here?

**Comment by adubovikov** [comment]
did you upgrade the docker-container to the latest one ?

**Comment by Mihai-CMM** [comment]
Thank you for reply,

Yes still not all the methods are exposed

![image](https://user-images.githubusercontent.com/14325493/74430545-5e586d80-4e5d-11ea-9942-90bbff1b280a.png)


In grafana this is te query
(rate(heplify_method_response{method="INVITE", response=~"50.*"}[10m]))


Docker images

```

> [root@homer-prod prometheus]# docker images
> REPOSITORY                  TAG                 IMAGE ID            CREATED             SIZE
> grafana/grafana             master              957fddf83da4        31 minutes ago      235MB
> grafana/loki                master              9026a538507f        15 hours ago        47.5MB
> sipcapture/webapp           latest              c9f78e3be0f2        20 hours ago        32.8MB
> sipcapture/heplify-server   master              83e5530f95ad        13 days ago         22.2MB
> postgres                    11-alpine           89ae06c2ad76        2 weeks ago         152MB
> prom/prometheus             latest              b715301fa5eb        5 weeks ago         133MB
> prom/alertmanager           latest              0881eb8f169f        2 months ago        52.1MB
> prom/node-exporter          latest              e5a616e4b9cf        8 months ago        22.9MB
> stefanprodan/caddy          latest              655880563633        2 years ago         24.7MB


```

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer7-docker

**Comment by Mihai-CMM** [comment]
Sorry @adubovikov I don't understand the comment, what should I do?

**Comment by adubovikov** [comment]
please install homer7-docker, not homer-docker

**Comment by Mihai-CMM** [comment]
Hmm, please excuse my noobness, is not what I am doying?

[root@homer-prod heplify-server]# git status
On branch 7.7
Your branch is up to date with 'origin/7.7'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

 

`* 7.7                     8c69dcd Merge branch '7.7' of https://github.com/sipcapture/homer7-docker into 7.7
  master                  c9594d3 [behind 22] Merge branch 'master' of https://github.com/sipcapture/homer7-docker
`

**Comment by lmangani** [comment]
@Mihai-CMM you opened the issue on the wrong repository :) that's all he said

**Comment by Mihai-CMM** [comment]
Stupid me :) ... got it, You want me to move it there?
Thanks guys

**Comment by Mihai-CMM** [comment]
Anyway I've looked at your yesterday commit @lmangani and it seems it fixed the issue. Commenting
`#       "HEPLIFYSERVER_PROMTARGETIP=127.0.0.1"
 \#       "HEPLIFYSERVER_PROMTARGETNAME=local"
`
Did the trick

Thanks
